Import('env')

dependencies = ['tanklib']
src_files = env.Glob("src/*.cpp")
data_files =[env.Dir("data")]

builtData = env.Data(data_files)
d = env.RSync(env.Dir("$INSTALL_DIR/tank/data/"), data_files)
env.Depends(d, builtData)
env.AlwaysBuild(d)


prog = env.KProgram("tank", src_files, dependencies)
finalProduct = env.Install(env.Dir("$INSTALL_DIR/tank"), prog)
env.Alias("@Tank",finalProduct) 
env.Alias("@Tank",d) 

Default(finalProduct)